<?php

/**
 * Implements hook_preprocess_HOOK().
 *
 * Adds, and outputs data into the HTML of the page.
 */
function drupal_datalayer_preprocess_html(&$variables) {
  global $user;

  // Only act on users that are logged in.
  if (user_is_logged_in()) {
    $args = arg();

    $dataLayer = new DataLayer();

    // Generate custom dimension for user roles.
    // TODO: You will need to load a single user role to pass through to the
    // Data Layer here.
    $output_data['userRole'] = 'Example role';
    $dataLayer->set($output_data);

    // Add Ecommerce data to a specific page.
    // There is a risk here that a user could reload the page and send the data a second time.
    if ($args[0] === 'my-custom-page') {
      if ($ecommerce_data = $dataLayer->getEcommerce($user->uid)) {
        $dataLayer->set($ecommerce_data);
      };
    }

    $output = $dataLayer->build();
    $dataLayer->render($output);
  }
}
